# Generated by Django 3.1.2 on 2020-10-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('wishlist_position', models.PositiveIntegerField(null=True)),
                ('playlist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_user', to='jukebox.playlist')),
                ('wishlist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_user', to='jukebox.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uri', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('image', models.URLField()),
                ('position', models.PositiveIntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='jukebox.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='searchresult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='jukebox.searchresult'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_playlist_and_position'),
        ),
    ]
