# Generated by Django 3.1.2 on 2020-10-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='searchresult',
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='jukebox.playlist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='playlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_of', to='jukebox.playlist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_of', to='jukebox.playlist'),
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
